In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("/home/fm-pc-lt-228/Desktop/covid_nepali_tweets/covid19_tweeter_dataset (copy).csv")

In [3]:
data

Unnamed: 0  Label                   Datetime  \
0             0.0     -1  2021-01-10 22:06:41+00:00   
1             1.0     -1  2021-01-10 17:49:34+00:00   
2             2.0      1  2021-01-10 16:18:34+00:00   
3             3.0      0  2021-01-10 15:12:17+00:00   
4             4.0     -1  2021-01-10 15:07:12+00:00   
...           ...    ...                        ...   
35395         NaN      0                       1238   
35396         NaN      0                       1239   
35397         NaN      0                       1240   
35398         NaN      0                       1241   
35399         NaN      0                       1242   

                                                   Tweet  \
0      अमेरिकामा कोभिड बाट एकै दिन चार हजारभन्दा बढीक...   
1      कोभिड का कारण विदेशमा रहेका नेपालीहरुमा मानसिक...   
2      नेपालमा क्लोभर बायोफार्मास्युटिकल्स अस्ट्रेलिय...   
3                                कोभिड को खोप पनि लगाइयो   
4      अमेरिकामा कोभिड को नयाँ रेकर्ड एकै दिन हजारभन्...   
...                                                  ...   
35395  यसरी त म २० पन्ना भएनी देखाउछु उत्ता गएर फोनमा...   
35396  बजारमा भित्रिए नयाँ Bijaya Shahi शाही, बल्ल सा...   
35397                                             कसो हो   
35398                    अबो यो मिडिया पनि सिदिने भो हहह   
35399                           य उहाँ मेमरी किङ्ग पो ho   

                                          Tokanize_tweet Unnamed: 5  
0      अमेरिकामा,कोभिड,बाट,एकै,दिन,चार,हजारभन्दा,बढीक...        NaN  
1      कोभिड,का,कारण,विदेशमा,रहेका,नेपालीहरुमा,मानसिक...        NaN  
2      नेपालमा,क्लोभर,बायोफार्मास्युटिकल्स,अस्ट्रेलिय...        NaN  
3                                कोभिड,को,खोप,पनि,लगाइयो        NaN  
4      अमेरिकामा,कोभिड,को,नयाँ,रेकर्ड,एकै,दिन,हजारभन्...        NaN  
...                                                  ...        ...  
35395  कोभिड,यत्रो,जोखिम,त्रास,हुॅदा,प्रदेश,स्थानीय,स...        NaN  
35396  बर्षिय,स्पेनिस,फुटबल,कोचको,कोभिड,संक्रमणबाट,मृ...        NaN  
35397  भरतपुर,महानगरपालिका,चितवन,प्रदर्शनी,केन्द्रमा,...        NaN  
35398  कोरोना,भाईरस,कोभिड,आयरल्याण्ड,क्रिकेट,टिमको,जि...        NaN  
35399  एकाएक,कोभिड,फलो,गरेछ,सक्कली,अहिलेसम्म,नेपाल,सक...        NaN  

[35400 rows x 6 columns]

In [4]:
data['Tweet'][30]

'प्रधानमँत्रीज्यू चुनाव गर्ने पैसा हुने तर कोभीड बाट जनताको लागि निशूल्क खोप ल्याउन पैसा नहुने खोप ल्याउन किन ढिलाइ गरिँदैछ देश र जनताप्रति किन लापरबाही'

In [5]:
data['length'] = data['Tokanize_tweet'].apply(
    lambda row: min(len(row.split(",")), len(row)) if isinstance(row, str) else None
)

In [6]:
max(data['length'].tolist())

61.0

In [7]:
data["Tweet"][1]

'कोभिड का कारण विदेशमा रहेका नेपालीहरुमा मानसिक स्वास्थ्य सम्बन्धि समस्या देखिएको र आत्महत्याका घटनाहरु बढेको डा सापकोटाले बताए'

In [8]:
data.head()

Unnamed: 0  Label                   Datetime  \
0         0.0     -1  2021-01-10 22:06:41+00:00   
1         1.0     -1  2021-01-10 17:49:34+00:00   
2         2.0      1  2021-01-10 16:18:34+00:00   
3         3.0      0  2021-01-10 15:12:17+00:00   
4         4.0     -1  2021-01-10 15:07:12+00:00   

                                               Tweet  \
0  अमेरिकामा कोभिड बाट एकै दिन चार हजारभन्दा बढीक...   
1  कोभिड का कारण विदेशमा रहेका नेपालीहरुमा मानसिक...   
2  नेपालमा क्लोभर बायोफार्मास्युटिकल्स अस्ट्रेलिय...   
3                            कोभिड को खोप पनि लगाइयो   
4  अमेरिकामा कोभिड को नयाँ रेकर्ड एकै दिन हजारभन्...   

                                      Tokanize_tweet Unnamed: 5  length  
0  अमेरिकामा,कोभिड,बाट,एकै,दिन,चार,हजारभन्दा,बढीक...        NaN     9.0  
1  कोभिड,का,कारण,विदेशमा,रहेका,नेपालीहरुमा,मानसिक...        NaN    18.0  
2  नेपालमा,क्लोभर,बायोफार्मास्युटिकल्स,अस्ट्रेलिय...        NaN    20.0  
3                            कोभिड,को,खोप,पनि,लगाइयो        NaN     5.0  
4  अमेरिकामा,कोभिड,को,नयाँ,रेकर्ड,एकै,दिन,हजारभन्...        NaN    12.0

In [9]:
data["Tokanize_tweet"][1]

'कोभिड,का,कारण,विदेशमा,रहेका,नेपालीहरुमा,मानसिक,स्वास्थ्य,सम्बन्धि,समस्या,देखिएको,र,आत्महत्याका,घटनाहरु,बढेको,डा,सापकोटाले,बताए'

In [10]:
data["Label"].value_counts()

 1    14998
-1    13606
 0     6796
Name: Label, dtype: int64

In [11]:
import torch
import numpy as np 
import pandas as pd 
from transformers import BertTokenizer, BertModel, BertForMaskedLM, AutoTokenizer, AutoModelForMaskedLM
from scipy.spatial.distance import cosine 
import tokenizers 
import pandas as pd 
from sklearn.model_selection import train_test_split,GridSearchCV
from sklearn.metrics import classification_report, confusion_matrix, f1_score, accuracy_score
from nltk.corpus import stopwords
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler
# import snowballstemmer
import numpy
import os 
import re
import json
import pickle 

In [12]:
model = AutoModelForMaskedLM.from_pretrained("Shushant/nepaliBERT", output_hidden_states = True, return_dict = True, output_attentions = True)

In [13]:
tokenizers = AutoTokenizer.from_pretrained("Shushant/nepaliBERT")

pickle.dump(model, open('bert_embeddings','wb'))

pickle.dump(tokenizers, open('bert_tokenizers','wb'))

model = pickle.load(open('bert_embeddings','rb'))
tokenizers= pickle.load(open('bert_tokenizers','rb'))

In [14]:
tokenizers.tokenize("के मौजुदा लोकतान्त्रिक व्यवस्था राज्य पुनःसंरचनासँग जोडिएका हिजोका सवालहरूलाई यथास्थितिमा छोडेर सबल होला?")

['क',
 'मौ',
 '##ज',
 '##दा',
 'लोक',
 '##तान',
 '##तर',
 '##िक',
 'वय',
 '##वस',
 '##था',
 'राज',
 '##य',
 'पन',
 '##ः',
 '##सर',
 '##चना',
 '##सग',
 'जोडिएका',
 'हिजोका',
 'सवाल',
 '##हर',
 '##लाई',
 'यथा',
 '##स',
 '##थिति',
 '##मा',
 'छोड',
 '##र',
 'सबल',
 'होला',
 '?']

In [15]:
def get_bert_embedding_sentence(input_sentence):
    md = model
    tokenizer = tokenizers
#     md = local_model
#     tokenizer = local_tokenizers
    marked_text = " [CLS] " + input_sentence + " [SEP] "
    tokenized_text = tokenizer.tokenize(marked_text)

    indexed_tokens = tokenizer.convert_tokens_to_ids(tokenized_text)
    segments_ids = [1] * len(indexed_tokens) 
    
    # Convert inputs to Pytorch tensors
    tokens_tensors = torch.tensor([indexed_tokens])
    segments_tensors = torch.tensor([segments_ids])
    
    with torch.no_grad():
        outputs = md(tokens_tensors, segments_tensors)
        # removing the first hidden state
        # the first state is the input state 

        hidden_states = outputs.hidden_states
#         print(hidden_states[-2])
        # second_hidden_states = outputs[2]
    # hidden_states has shape [13 x 1 x 22 x 768]

    # token_vecs is a tensor with shape [22 x 768]
#     token_vecs = hidden_states[-2][0]
    # get last four layers
#     last_four_layers = [hidden_states[i] for i in (-1,-2, -3,-4)]
    # cast layers to a tuple and concatenate over the last dimension
#     cat_hidden_states = torch.cat(tuple(last_four_layers), dim=-1)
#     print(cat_hidden_states.shape)
    token_vecs = hidden_states[-2][0]
    # take the mean of the concatenated vector over the token dimension
#     sentence_embedding = torch.mean(cat_hidden_states, dim=0).squeeze()

    # Calculate the average of all 22 token vectors.
    sentence_embedding = torch.mean(token_vecs, dim=0)
#     sentence_embedding = torch.mean(token_vecs, dim=1)
    return sentence_embedding.numpy()

In [16]:
data["Tweet"][0]

'अमेरिकामा कोभिड बाट एकै दिन चार हजारभन्दा बढीको मृत्यु'

In [17]:
data['word_embeddings'] = data['Tweet'].apply(get_bert_embedding_sentence)

In [26]:
data.to_csv("embeddings_data.csv")

In [18]:
X,y = data['word_embeddings'], data['Label']

In [19]:
train_X, test_X, train_y, test_y = train_test_split(X,y, test_size = 0.2, random_state = 420)

train_df,test_df = train_test_split(data, test_size = 0.2, random_state = 420)

train_df.to_csv("train.csv")

test_df.to_csv("test.csv")

In [20]:
svc = SVC(probability=True)

In [21]:
svc.fit(train_X.tolist(), train_y)
#svc.fit(train_X, train_y)

SVC(probability=True)

In [22]:
svc_pred = svc.predict(test_X.tolist())
# svc_pred = svc.predict(test_X)

In [23]:
print(confusion_matrix(test_y, svc_pred))

[[2232   53  441]
 [ 318  304  455]
 [ 511   52 2466]]


In [24]:
print(classification_report(test_y, svc_pred))

              precision    recall  f1-score   support

          -1       0.73      0.82      0.77      2726
           0       0.74      0.28      0.41      1077
           1       0.73      0.81      0.77      3029

    accuracy                           0.73      6832
   macro avg       0.74      0.64      0.65      6832
weighted avg       0.73      0.73      0.71      6832



In [25]:
accuracy_score(test_y, svc_pred)

0.7321428571428571

In [ ]:
sent = "नराम्रो"
predicted_label = svc.predict_proba(np.array(get_bert_embedding_sentence(sent).tolist()).reshape(1,-1))[0]
if predicted_label[0]<predicted_label[1]:
    print(f'{sent} is negative sentiment')
else:
    print(f'{sent} is positive sentiment')

In [25]:
from sklearn.ensemble import GradientBoostingClassifier
gbc = GradientBoostingClassifier(n_estimators=100, learning_rate=1.0,
    max_depth=1, random_state=0).fit(train_X.tolist(), train_y)
gbc.score(test_X.tolist(), test_y)

0.6766243465272591

In [26]:

from sklearn.linear_model import LogisticRegression
clf = LogisticRegression(random_state=0).fit(train_X.tolist(), train_y)



clf.score(test_X.tolist(), test_y)

/home/fm-pc-lt-228/anaconda3/envs/nepali/lib/python3.7/site-packages/sklearn/linear_model/_logistic.py:765: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.7047050037341299

In [27]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(train_X.tolist(), train_y)
gnb.score(test_X.tolist(), test_y)

0.5870052277819268

In [28]:
gnb_pred = gnb.predict(test_X.tolist())
print(confusion_matrix(test_y, gnb_pred))

[[1491  599  666]
 [ 124  473  387]
 [ 336  653 1966]]


## Deep Learning

In [29]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from keras.models import Model
from keras.layers import LSTM, Activation, Dense, Dropout, Input, Embedding
from keras.optimizers import RMSprop
from keras.preprocessing.text import Tokenizer
from keras.preprocessing import sequence
from keras.utils import to_categorical
from keras.callbacks import EarlyStopping
%matplotlib inline

2022-09-19 16:15:27.659036: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-09-19 16:15:27.682787: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-09-19 16:15:27.682799: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [28]:
data['word_embeddings'][0]

array([-1.05079815e-01,  6.60110891e-01,  3.57779235e-01,  9.07263815e-01,
        1.11969285e-01, -2.28671238e-01, -8.88476148e-02, -6.83927462e-02,
        1.48592234e-01, -1.53660014e-01,  1.89314857e-01,  2.41184011e-01,
        2.40040213e-01, -2.35330522e-01, -8.25594515e-02,  4.54757750e-01,
        3.78678322e-01, -4.91710782e-01, -5.43783940e-02, -2.33931094e-01,
        2.94030815e-01, -4.41250712e-01, -2.24258199e-01, -3.41822237e-01,
       -5.49264014e-01, -8.49143922e-01,  5.85750163e-01,  2.20755696e-01,
       -4.64857101e-01,  4.92242128e-01, -5.72632104e-02, -5.02846576e-02,
        3.37019265e-02, -4.17852759e-01,  1.03762947e-01, -4.72780734e-01,
       -3.54295187e-02,  3.08029979e-01,  1.62414331e-02,  2.00192213e-01,
        4.00807559e-01, -4.75480258e-01,  2.34706059e-01, -1.67396903e-01,
        2.97297001e-01,  4.75440264e-01, -4.63157415e-01,  2.17456490e-01,
       -1.44426808e-01, -1.16206385e-01, -2.52778262e-01, -1.54680514e+00,
        3.75086218e-02,  

In [29]:
from numpy import loadtxt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

2022-09-22 07:29:42.585951: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-09-22 07:29:42.673891: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-09-22 07:29:42.673977: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [51]:
Y_array = data['Label'].to_list()

In [52]:
Y = np.array(Y_array)

In [53]:
Y

array([-1, -1,  1, ...,  0,  0,  0])

In [65]:
from sklearn.preprocessing import LabelEncoder
from keras.utils import np_utils


# encode class values as integers
encoder = LabelEncoder()
encoder.fit(Y)
encoded_Y = encoder.transform(Y)
# convert integers to dummy variables (i.e. one hot encoded)
dummy_y = np_utils.to_categorical(encoded_Y)

In [41]:
x_array = data['word_embeddings'].to_list()

In [46]:
x = np.array(x_array)

In [58]:
x.shape

(34159, 768)

In [76]:
dummy_y.shape

(34159, 3)

In [77]:
x.shape

(34159, 768)

In [86]:
train_x, test_x, train_Y, test_Y = train_test_split(x,dummy_y, test_size = 0.2, random_state = 420)

In [115]:
from keras.wrappers.scikit_learn import KerasClassifier
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# define baseline model
def baseline_model():
    # create model
    model = Sequential()
    model.add(Dense(100, input_dim=768, activation='relu'))
    model.add(Dense(50, activation='relu'))
    model.add(Dense(25,activation="relu"))
    model.add(Dense(3, activation='softmax'))
    # Compile model
    model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model
 
# estimator = KerasClassifier(build_fn=baseline_model, epochs=2, batch_size=5, verbose=1)
# kfold = KFold(n_splits=2, shuffle=True)
# results = cross_val_score(estimator, x,dummy_y, cv=kfold)
# print("Baseline: %.2f%% (%.2f%%)" % (results.mean()*100, results.std()*100))

In [116]:
model = baseline_model()
model.fit( train_x,train_Y, epochs=20, batch_size=10)

Epoch 1/20
2733/2733 [==============================] - 10s 3ms/step - loss: 0.7325 - accuracy: 0.6860
Epoch 2/20
2733/2733 [==============================] - 9s 3ms/step - loss: 0.6749 - accuracy: 0.7134
Epoch 3/20
2733/2733 [==============================] - 9s 3ms/step - loss: 0.6521 - accuracy: 0.7229
Epoch 4/20
2733/2733 [==============================] - 9s 3ms/step - loss: 0.6290 - accuracy: 0.7330
Epoch 5/20
2733/2733 [==============================] - 10s 4ms/step - loss: 0.6070 - accuracy: 0.7440
Epoch 6/20
2733/2733 [==============================] - 10s 4ms/step - loss: 0.5875 - accuracy: 0.7519
Epoch 7/20
2733/2733 [==============================] - 10s 4ms/step - loss: 0.5674 - accuracy: 0.7612
Epoch 8/20
2733/2733 [==============================] - 9s 3ms/step - loss: 0.5505 - accuracy: 0.7690
Epoch 9/20
2733/2733 [==============================] - 9s 3ms/step - loss: 0.5346 - accuracy: 0.7752
Epoch 10/20
2733/2733 [==============================] - 9s 3ms/step - loss: 0

In [ ]:
x_train = np.asarray(x_train).astype(np.float32)
y_train = np.asarray(y_train).astype(np.float32)

In [117]:
model.evaluate(test_x,test_Y)

214/214 [==============================] - 1s 3ms/step - loss: 0.8656 - accuracy: 0.7168


[0.8656483888626099, 0.7167739868164062]

In [118]:
predictions = model.predict(test_x)

214/214 [==============================] - 1s 2ms/step


In [119]:
pred = np.argmax(predictions, axis=1)

In [120]:
pred

array([2, 2, 2, ..., 0, 0, 0])

In [121]:
encoded_test_y = np.argmax(test_Y,axis=1)

In [122]:
print(confusion_matrix(encoded_test_y, pred))

[[2129  152  445]
 [ 243  521  313]
 [ 516  266 2247]]


In [123]:
print(classification_report(encoded_test_y, pred))

              precision    recall  f1-score   support

           0       0.74      0.78      0.76      2726
           1       0.55      0.48      0.52      1077
           2       0.75      0.74      0.74      3029

    accuracy                           0.72      6832
   macro avg       0.68      0.67      0.67      6832
weighted avg       0.71      0.72      0.71      6832



In [48]:
from sklearn.model_selection import cross_val_score
from sklearn.datasets import make_blobs
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier

X = train_X.to_list()
y = train_y

clf = DecisionTreeClassifier(max_depth=None, min_samples_split=2,
    random_state=0)
scores = cross_val_score(clf, X, y, cv=5)
scores.mean()

0.5566671408418981

In [49]:
clf = RandomForestClassifier(n_estimators=10, max_depth=None,
    min_samples_split=2, random_state=0)
scores = cross_val_score(clf, X, y, cv=5)
scores.mean()

0.6459912598347778

In [50]:
clf = ExtraTreesClassifier(n_estimators=10, max_depth=None,
    min_samples_split=2, random_state=0)
scores = cross_val_score(clf, X, y, cv=5)
scores.mean() 

0.6438628545767323

## Finetuning with NepBERT

In [16]:
from transformers import AutoModelForSequenceClassification

model = AutoModelForSequenceClassification.from_pretrained("Shushant/nepaliBERT", num_labels=3)

Some weights of the model checkpoint at Shushant/nepaliBERT were not used when initializing BertForSequenceClassification: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.decoder.bias', 'cls.predictions.decoder.weight', 'cls.predictions.transform.dense.bias', 'cls.predictions.transform.LayerNorm.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.bias']
- This IS expected if you are initializing BertForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Some weights of BertForSequenceClassification were not initialized from the model checkpoint at Shushant/nepaliBERT and a

In [17]:
import numpy as np
import evaluate

metric = evaluate.load("accuracy")

2022-09-17 22:53:52.854163: I tensorflow/core/util/util.cc:169] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2022-09-17 22:53:52.878462: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory
2022-09-17 22:53:52.878476: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.


In [18]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(predictions=predictions, references=labels)

In [19]:
from datasets import load_dataset

dataset = load_dataset("Shushant/CovidNepaliTweets")
dataset["train"][100]

Using custom data configuration Shushant--CovidNepaliTweets-00a71fabf99a7743
Reusing dataset csv (/home/fm-pc-lt-228/.cache/huggingface/datasets/Shushant___csv/Shushant--CovidNepaliTweets-00a71fabf99a7743/0.0.0/652c3096f041ee27b04d2232d41f10547a8fecda3e284a79a0ec4053c916ef7a)


  0%|          | 0/2 [00:00<?, ?it/s]

{'Label': 0,
 'Text': 'नेपाली कांग्रेसका वरिष्ठनेता अादरणिय श्री रामचन्द्र पौडेलज्यूको प्रमुख अातिथ्यतामा कोभिड पछिको विश्वसन्दर्भमा लोकतान्त्रिक समाजबादको सान्दर्भिकता विषयक प्रदेश स्तरिय जुम मिटिङ्ग फेसबुकमा गते जेष्ठ बुधबार बजे लाईभ गरिनेछ सामाजिक लोकतन्त्र अध्ययन केन्द्र'}

In [28]:
from transformers import AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained("Shushant/nepaliBERT")

max_length = 61
def tokenize_function(examples):
    return tokenizer(examples['Text'], padding='max_length', truncation=True, max_length=max_length)


tokenized_datasets = dataset.map(tokenize_function, batched=True)

Could not locate the tokenizer configuration file, will try to use the model config instead.
loading configuration file https://huggingface.co/Shushant/nepaliBERT/resolve/main/config.json from cache at /home/fm-pc-lt-228/.cache/huggingface/transformers/c642996ea6b3b6351e3519c0b5059b07a6b8a1a8e4961bf81d181326b75cabfe.3abddfe906646a59813d34e11ed576b8ddb2023553640fa3ce71f000d3c234d0
Model config BertConfig {
  "_name_or_path": "Shushant/nepaliBERT",
  "architectures": [
    "BertForMaskedLM"
  ],
  "attention_probs_dropout_prob": 0.1,
  "classifier_dropout": null,
  "hidden_act": "gelu",
  "hidden_dropout_prob": 0.1,
  "hidden_size": 768,
  "initializer_range": 0.02,
  "intermediate_size": 3072,
  "layer_norm_eps": 1e-12,
  "max_position_embeddings": 512,
  "model_type": "bert",
  "num_attention_heads": 12,
  "num_hidden_layers": 12,
  "pad_token_id": 0,
  "position_embedding_type": "absolute",
  "torch_dtype": "float32",
  "transformers_version": "4.15.0",
  "type_vocab_size": 2,
  "use_

  0%|          | 0/27 [00:00<?, ?ba/s]

  0%|          | 0/7 [00:00<?, ?ba/s]

In [29]:
tokenized_datasets['train'][0]

{'Label': 1,
 'Text': 'आचार्य जी हर बिमारी का इलाज ढुढलेते हैं आप अब तक कोभीड का कोइ इलाज वा दवा क्यों नहिं खोज पाए हैं',
 'input_ids': [2,
  8575,
  1022,
  2260,
  2699,
  7590,
  1714,
  1701,
  9525,
  1037,
  380,
  1061,
  4102,
  402,
  4167,
  2227,
  30176,
  1805,
  4690,
  1051,
  1701,
  3615,
  9525,
  1037,
  1862,
  8773,
  367,
  1700,
  11992,
  1027,
  2426,
  4583,
  402,
  4,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'token_type_ids': [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0],
 'attention_mask': [1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1,
  1

In [30]:
len(tokenized_datasets['train'][0]['attention_mask'])

61

In [35]:
small_train_dataset = tokenized_datasets["train"].shuffle(seed=42).select(range(1000))
small_eval_dataset = tokenized_datasets["test"].shuffle(seed=42).select(range(1000))

In [36]:
from transformers import TrainingArguments, Trainer

training_args = TrainingArguments(output_dir="test_trainer", evaluation_strategy="epoch")

PyTorch: setting up devices
The default value for the training argument `--report_to` will change in v5 (from all installed integrations to none). In v5, you will need to use `--report_to all` to get the same behavior as now. You should start updating your code and make this info disappear :-).


In [37]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=small_train_dataset,
    eval_dataset=small_eval_dataset,
    compute_metrics=compute_metrics,
)

In [38]:
trainer.train()

The following columns in the training set  don't have a corresponding argument in `BertForSequenceClassification.forward` and have been ignored: Label, Text.
***** Running training *****
  Num examples = 1000
  Num Epochs = 3
  Instantaneous batch size per device = 8
  Total train batch size (w. parallel, distributed & accumulation) = 8
  Gradient Accumulation steps = 1
  Total optimization steps = 375


RuntimeError: CUDA error: no kernel image is available for execution on the device
CUDA kernel errors might be asynchronously reported at some other API call,so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.